version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8 # Runtime version is required in the build spec even though this module does not use java
  build:
    commands:
      - bin/package.sh -n analytics
artifacts:
  files:
    - analytics/target/sam/app/packaged-template.yaml
  discard-paths: yes
