version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      nodejs: 8
    commands:
      - npm install -g @vue/cli
  build:
    commands:
      - npm install --prefix aws-serverless-app-repo-reference-static-website
      - npm run ci --prefix aws-serverless-app-repo-reference-static-website
      - mvn clean package -DpackageBucket=${PACKAGE_BUCKET}
