version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      # Remove the first three lines once aws-ssm-caching-client is published to Maven Central Repository
      - cd aws-ssm-caching-client
      - mvn clean install
      - cd ..
      - cd realworld-serverless-application-backend
      - mvn clean package -DpackageBucket=${PACKAGE_BUCKET}
artifacts:
  files:
    - realworld-serverless-application-backend/target/sam/app/packaged-template.yaml
  discard-paths: yes
