AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  This application creates a backend service using serverless technologies such as API Gateway, Lambda etc.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: realworld-serverless-application-backend
    Description: >-
      This application creates a backend service using serverless technologies such as API Gateway, Lambda etc.
    Author: AWS Serverless Application Repository
    SpdxLicenseId: Apache-2.0
    Labels: [github, serverless, sam]
    HomePageUrl: https://github.com/awslabs/realworld-serverless-application
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/awslabs/realworld-serverless-application/tree/1.0.0
    LicenseUrl: ../../../LICENSE
    ReadmeUrl: ../../README.md

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'test'

Resources:
  Api:
    Type: 'AWS::Serverless::Application'
    Properties:
      Location: 'api.template.yaml'
      Parameters:
        Stage: !Ref Stage
    DependsOn: Database
  Database:
    Type: 'AWS::Serverless::Application'
    Properties:
      Location: 'database.template.yaml'
      Parameters:
        Stage: !Ref Stage
