version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      # Remove the first three lines once aws-ssm-caching-client is published to Maven Central Repository
      - cd aws-ssm-caching-client
      - mvn clean install
      - cd ..
      - cd aws-serverless-app-repo-reference-backend
      - STAGE=integ-tests-`date +%s`
      - mvn clean verify -Dintegtests.stage=${STAGE}

