AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  This template creates IAM roles and use them to setup CD pipeline for the ops component.

Parameters:
  GitHubOAuthTokenSecretId:
    Type: String
    Description: The AWS Secrets Manager Secret Id that stores Github OAuth token.
    Default: 'GitHubOAuthToken'
  GitHubOwner:
    Type: String
    Description: The GitHub owner of the repository.
    Default: 'awslabs'
  ApplicationStackName:
    Type: String
    Description: The stack name the CICD will deploy the application to.
    Default: 'realworld-serverless-application-ops'
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'
Resources:
  CD:
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:646794253159:applications/aws-sam-codepipeline-cd
        SemanticVersion: 0.1.3
      Parameters:
        GitHubOAuthToken: !Sub '{{resolve:secretsmanager:${GitHubOAuthTokenSecretId}}}'
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: realworld-serverless-application
        DeployStackName: !Ref ApplicationStackName
        DeployRoleName: !Ref DeployRole
        DeployParameterOverrides: !Sub '{"Stage":"${Stage}"}'
        BuildSpecFilePath: 'ops/buildspec.yaml'

  # This policy defines the minimum IAM permissions required to Create and Delete a stack for ops component into CloudFormation
  CloudFormationDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref DeployRole
      PolicyName: "deploy-create-delete-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - cloudformation:CreateChangeSet
            Resource:
              - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31
              - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:aws:transform/Include
          - Effect: "Allow"
            Action:
              - sns:CreateTopic
              - sns:GetTopicAttributes
              - sns:DeleteTopic
            Resource:
              - !Sub arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${ApplicationStackName}-*
          - Effect: "Allow"
            Action:
              - cloudwatch:PutDashboard
              - cloudwatch:DeleteDashboards
            Resource: 
              - !Sub arn:${AWS::Partition}:cloudwatch::${AWS::AccountId}:dashboard/*
          - Effect: "Allow"
            Action:
              - cloudwatch:PutMetricAlarm
              - cloudwatch:DeleteAlarms
            Resource:
              - !Sub arn:${AWS::Partition}:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${ApplicationStackName}-*
          - Effect: "Allow"
            Action:
              - ssm:PutParameter
              - ssm:DeleteParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
              - ssm:AddTagsToResource
              - ssm:RemoveTagsFromResource
            Resource:
              - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/applications/apprepo/*

  # This role is used to deploy realworld-serverless-application-ops to CloudFormation.
  DeployRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: !Sub "Deploy CloudFormation stack ${ApplicationStackName}. Created by CloudFormation ${AWS::StackId}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
