version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install -g @vue/cli
  build:
    commands:
      - ./aws-serverless-app-repo-reference-static-website/bin/package-static-website.sh
      - ./bin/package.sh -n aws-serverless-app-repo-reference-static-website
artifacts:
  files:
    - aws-serverless-app-repo-reference-static-website/target/sam/app/packaged-template.yaml
  discard-paths: yes